#!/bin/sh
#
# $Id: kicker,v 1.2 2007/09/05 22:20:01 iku Exp $
# 
# Copyright (c) 2007 Antti Harri <iku@openbsd.fi>
#

# "Boot up" script. Run from rc.local.

# paths where to look for installed utilities
PATH=/root/bin:/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin
BASE=$(cd -- "$(dirname -- "$0")"; pwd)

while true; do 
	pgrep -U 0 -x 'cleanfs' || ${BASE}/cleanfs
	sleep 30
done
