#!/bin/sh
#
# $Id: logger,v 1.2 2008/03/10 18:10:09 iku Exp $
#
# Copyright (c) 2007 Antti Harri <iku@openbsd.fi>
#

BASE=$(cd -- "$(dirname -- "$0")"; pwd)
lockdir="${BASE}/.logger.lock"
logfile="${BASE}/logs/system.log"

if [ -n "$1" ]; then
	logfile=$1
fi

# Prevent race condition. Code from Lasse Collin.
while ! mkdir "$lockdir" 2> /dev/null ; do 
	sleep 1
done
trap "rmdir \"$lockdir\"" EXIT

# Log parameters
while read -r stdin; do
	cat >> "$logfile"
done
