#!/bin/sh
#
# $Id: create_DBs,v 1.1 2008/11/08 07:51:01 iku Exp $
#
# Copyright (c) 2008,2009 Antti Harri <iku@openbsd.fi>
#

BASE=$(cd -- "$(dirname -- "$0")"; pwd)"/.."

# Default umask.
umask 077

if [ ! -e "$BASE/config/backup.conf" ]; then
	echo "Edit configuration: $BASE/config/backup.conf"
	exit 1
fi

# Pick up functions & defaults.
. "$BASE/share/functions.sh"
. "$BASE/share/opsys.sh"
. "$BASE/share/helpers.sh"
. "$BASE/config/backup.conf"

cd "${backups}" || exit 1

# (backups) / hosts / filters / snapshots
for backup_job in $backup_jobs; do
	# Get _target, _user, _host and _login
	parse_target "$backup_job"
	cd "${backups}/${_login}/" || continue
	create_db ./ locate.db
done
