#!/bin/sh
#
# Copyright (c) 2008,2009 Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

set -u

BASE=$(cd -- "$(dirname -- "$0")"; pwd)"/.."

# Default umask.
umask 077

if [ ! -e "$BASE/config/backup.conf" ]; then
	echo "Edit configuration: $BASE/config/backup.conf"
	exit 1
fi

# Pick up functions & defaults.
. "$BASE/share/opsys.sh"
. "$BASE/share/functions.sh"
. "$BASE/share/helpers.sh"
. "$BASE/config/backup.conf"

for backup_job in $backup_jobs; do
	# Get _src, _src_user, _src_host and _src_login
	parse_target "$backup_job"
	case "$backup_mode" in
		filecopy|pull)	cd "$_dst_dir" || continue ;;
		push)		echo "Push mode not supported." ; continue ;;
	esac
	create_db ./ locate.db
done
