#!/bin/sh
#
# $Id: genkey,v 1.1 2007/09/14 20:14:00 iku Exp $
#
# Copyright (c) 2007 Antti Harri <iku@openbsd.fi>
#

BASE=$(cd -- "$(dirname -- "$0")"; pwd)

ssh-keygen -N '' -t rsa -f "$BASE/../config/ssh_key"

if [ "$?" -eq 0 ]; then
	echo "You should now place the public key into clients' authorized_keys"
	echo "See the contents of .pub and paste it for example"
fi
