#!/bin/sh

# Copyright (c) 2011 Antti Harri <iku@openbsd.fi>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

# Example script to trigger backups when the correct
# USB disc has been plugged in. The disk in question
# is encrypted for extra protection, which will
# be opened with bioctl, resulting disk mounted
# and finally the backup script will be started
# that is inside the disk.

set -u

# Fill in with your disk uids
cryptodev=a2d2046a303e5e58.d
backupdev=969a60a2dc7cdb7f.d
mntpoint=/backups

echo 'Assembling encrypted volumes'
until bioctl -c C -l "$cryptodev" softraid0
do echo -n 'try again ' ; sleep 1
done
fsck -p "$backupdev"
mount "$mntpoint"
cd "$mntpoint"/backupper-server/
./backup
cd /
umount "$mntpoint"
duid=$(echo "$backupdev" | cut -f 1 -d '.')
bioctl -d "$duid"
